plugins:
  - rubocop-minitest
  - rubocop-rake

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

AllCops:
  NewCops: enable
